[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
authors = ["snowmang1 evanmdrake@icloud.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo = "0.6.1"
yew = "0.19"
web-sys = "0.3.56"
